export const GET_TAGS = "GET_TAGS";
export const GET_ASSETS = "GET_ASSETS";
export const SEARCH_VALUE_DASHBOARDPAGE = "SEARCH_VALUE_DASHBOARDPAGE";
export const SEARCH_VALUE_LANDINGPAGE = "SEARCH_VALUE_LANDINGPAGE";
export const GET_SUBTAGS = "GET_SUBTAGS";
export const SELECT_FILTER = "SELECT_FILTER";
